# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/nghiaround/homebrew/Cellar/cmake/3.7.2/bin/cmake

# The command to remove a file.
RM = /Users/nghiaround/homebrew/Cellar/cmake/3.7.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/nghiaround/rec_table

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/nghiaround/rec_table

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/nghiaround/homebrew/Cellar/cmake/3.7.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/nghiaround/homebrew/Cellar/cmake/3.7.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nghiaround/rec_table/CMakeFiles /Users/nghiaround/rec_table/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nghiaround/rec_table/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named extract_cell

# Build rule for target.
extract_cell: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 extract_cell
.PHONY : extract_cell

# fast build rule for target.
extract_cell/fast:
	$(MAKE) -f CMakeFiles/extract_cell.dir/build.make CMakeFiles/extract_cell.dir/build
.PHONY : extract_cell/fast

debug_util.o: debug_util.cpp.o

.PHONY : debug_util.o

# target to build an object file
debug_util.cpp.o:
	$(MAKE) -f CMakeFiles/extract_cell.dir/build.make CMakeFiles/extract_cell.dir/debug_util.cpp.o
.PHONY : debug_util.cpp.o

debug_util.i: debug_util.cpp.i

.PHONY : debug_util.i

# target to preprocess a source file
debug_util.cpp.i:
	$(MAKE) -f CMakeFiles/extract_cell.dir/build.make CMakeFiles/extract_cell.dir/debug_util.cpp.i
.PHONY : debug_util.cpp.i

debug_util.s: debug_util.cpp.s

.PHONY : debug_util.s

# target to generate assembly for a file
debug_util.cpp.s:
	$(MAKE) -f CMakeFiles/extract_cell.dir/build.make CMakeFiles/extract_cell.dir/debug_util.cpp.s
.PHONY : debug_util.cpp.s

extract_cell.o: extract_cell.cpp.o

.PHONY : extract_cell.o

# target to build an object file
extract_cell.cpp.o:
	$(MAKE) -f CMakeFiles/extract_cell.dir/build.make CMakeFiles/extract_cell.dir/extract_cell.cpp.o
.PHONY : extract_cell.cpp.o

extract_cell.i: extract_cell.cpp.i

.PHONY : extract_cell.i

# target to preprocess a source file
extract_cell.cpp.i:
	$(MAKE) -f CMakeFiles/extract_cell.dir/build.make CMakeFiles/extract_cell.dir/extract_cell.cpp.i
.PHONY : extract_cell.cpp.i

extract_cell.s: extract_cell.cpp.s

.PHONY : extract_cell.s

# target to generate assembly for a file
extract_cell.cpp.s:
	$(MAKE) -f CMakeFiles/extract_cell.dir/build.make CMakeFiles/extract_cell.dir/extract_cell.cpp.s
.PHONY : extract_cell.cpp.s

line_util.o: line_util.cpp.o

.PHONY : line_util.o

# target to build an object file
line_util.cpp.o:
	$(MAKE) -f CMakeFiles/extract_cell.dir/build.make CMakeFiles/extract_cell.dir/line_util.cpp.o
.PHONY : line_util.cpp.o

line_util.i: line_util.cpp.i

.PHONY : line_util.i

# target to preprocess a source file
line_util.cpp.i:
	$(MAKE) -f CMakeFiles/extract_cell.dir/build.make CMakeFiles/extract_cell.dir/line_util.cpp.i
.PHONY : line_util.cpp.i

line_util.s: line_util.cpp.s

.PHONY : line_util.s

# target to generate assembly for a file
line_util.cpp.s:
	$(MAKE) -f CMakeFiles/extract_cell.dir/build.make CMakeFiles/extract_cell.dir/line_util.cpp.s
.PHONY : line_util.cpp.s

preprocessing.o: preprocessing.cpp.o

.PHONY : preprocessing.o

# target to build an object file
preprocessing.cpp.o:
	$(MAKE) -f CMakeFiles/extract_cell.dir/build.make CMakeFiles/extract_cell.dir/preprocessing.cpp.o
.PHONY : preprocessing.cpp.o

preprocessing.i: preprocessing.cpp.i

.PHONY : preprocessing.i

# target to preprocess a source file
preprocessing.cpp.i:
	$(MAKE) -f CMakeFiles/extract_cell.dir/build.make CMakeFiles/extract_cell.dir/preprocessing.cpp.i
.PHONY : preprocessing.cpp.i

preprocessing.s: preprocessing.cpp.s

.PHONY : preprocessing.s

# target to generate assembly for a file
preprocessing.cpp.s:
	$(MAKE) -f CMakeFiles/extract_cell.dir/build.make CMakeFiles/extract_cell.dir/preprocessing.cpp.s
.PHONY : preprocessing.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... extract_cell"
	@echo "... debug_util.o"
	@echo "... debug_util.i"
	@echo "... debug_util.s"
	@echo "... extract_cell.o"
	@echo "... extract_cell.i"
	@echo "... extract_cell.s"
	@echo "... line_util.o"
	@echo "... line_util.i"
	@echo "... line_util.s"
	@echo "... preprocessing.o"
	@echo "... preprocessing.i"
	@echo "... preprocessing.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

