# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesheet',
            name='url',
            field=models.CharField(help_text='File URL', max_length=254),
        ),
    ]
