# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesheet',
            name='username',
            field=models.CharField(default='unknown', help_text='Username', max_length=50),
        ),
    ]
