# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_imagesheet_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesheet',
            name='state',
            field=models.CharField(choices=[(('FR',), 'Fresh'), (('PI',), 'Processing'), (('DS',), 'Processed'), (('DE',), 'ProcessedWithError')], default=('FR',), max_length=2),
        ),
    ]
