# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_imagesheet_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesheet',
            name='url',
        ),
        migrations.AddField(
            model_name='imagesheet',
            name='file_id',
            field=models.CharField(default=2, help_text='File Id', max_length=120),
            preserve_default=False,
        ),
    ]
