# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_imagesheet_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='File URL', max_length=254)),
                ('expected_char', models.CharField(help_text='Expected character', max_length=1)),
                ('predicted_char', models.CharField(help_text='Predicted_character', max_length=1)),
                ('image_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ImageSheet')),
            ],
        ),
    ]
