# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_cell'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('num', models.CharField(help_text='Number field', max_length=4)),
                ('big', models.CharField(help_text='Big number field', max_length=3)),
                ('small', models.CharField(help_text='Small number field', max_length=3)),
                ('roll', models.CharField(help_text='Roll field R,K,I,r,k,i', max_length=1)),
                ('is_delete', models.CharField(help_text='is this line deleted', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ImageSheet')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cell',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
