# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20171105_0829'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expectedresult',
            unique_together=set([('image_sheet', 'order')]),
        ),
    ]
