# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20171013_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesheet',
            name='url',
            field=models.CharField(default=123, help_text='File URL', max_length=500),
            preserve_default=False,
        ),
    ]
