# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_imagesheet_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagesheet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
